### ISSUE TITLE
TypeError: inlinePlugin is not a function

### ISSUE THREAD

**Issue by hannojg** [molgenis/vite-plugin-inline#9]
Hey I am getting the following error:

```
➜ bun run build
$ tsc && vite build
failed to load config from /xxx/react-web-editor/vite.config.ts
error during build:
TypeError: inlinePlugin is not a function
    at file:///xxx/react-web-editor/vite.config.ts.timestamp-1696402326618-bd56a5152800c.mjs:6:22
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadConfigFromBundledFile (file:///xxx/react-web-editor/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:66319:21)
    at async loadConfigFromFile (file:///xxx/react-web-editor/node_modules/vite/dist/node/chunks/dep-3bba9c7e.js:66168:28)
error: script "build" exited with code 1 (SIGHUP)
```

with the following config:

```typescript
import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import inlinePlugin from '@molgenis/vite-plugin-inline/src/vite-plugin-inline.js';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), inlinePlugin()],
  build: {
    rollupOptions: {
      input: ['./index.html', '@molgenis/vite-plugin-inline/src/loader.ts'],
      output: {
        manualChunks: undefined,
      },
    },
  },
});
```

I created the project using:

```
bun create vite

> Select react 
> Select typescript
```

**Comment by hannojg** [comment]
I think the issue stems from the fact, that the plugin is in raw typescript and doesn't get shipped transpiled. I manually have to add it to my tsconfig.json so it gets build (could also be a bun.sh specific thing)
